[package]
name = "xhdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
ansi_term = "0.12.1"